# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Sphinx'
copyright = '2022, YC'
author = 'YC'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.imgconverter']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'fr'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['*/conf.py','wsl','docker','github','sphinx_design','pyodide']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#

html_theme = 'sphinx_book_theme'
# html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = ['custom.css']

# -- Options for LaTeX output ---------------------------------------------


latex_additional_files = ['mystyle.sty']
#latex_toplevel_sectioning = 'section'
#latex_engine = 'pdflatex'

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    'papersize': 'a4paper',
    'releasename':"",
    #'fncychap': '\\usepackage{fncychap}',
    'fontpkg': '\\usepackage{amsmath,amsfonts,amssymb,amsthm}',
    'geometry': '\\usepackage[a4paper,left=0.6in, right=0.6in, top=0.6in, bottom=0.6in]{geometry}',

    'figure_align':'htbp',
    # The font size ('10pt', '11pt' or '12pt').
    #
    'pointsize': '11pt',

    'preamble': r'''
    \usepackage{verbatim}
    \usepackage{fancyvrb}


    % Chargement de la feuille de style personnalisée défini dans le tableau latex_additionnal_files (ci-dessus)
    \input{mystyle.sty}
    ''',
    'sphinxsetup':r'''
    noteBorderColor={rgb}{0.53, 0.81, 0.98},
    tipBorderColor={rgb}{0.53, 0.81, 0.98},
    cautionBorderColor={rgb}{0.7, 0.93, 0.36},
    hintBorderColor={rgb}{0.7, 0.93, 0.36},
    warningBorderColor={rgb}{1.0, 0.25, 0.25},
    errorBorderColor={rgb}{1.0, 0.25, 0.25},
    importantBorderColor={rgb}{1.0, 0.25, 0.25},
    '''
}

latex_documents = [(master_doc, 'documentation.tex', 'Export en latex','Yannick Chistel','manual')]
